apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rqe-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "events"]
    verbs: ["get", "list", "watch", "delete", "create", "patch", "update"]
  - apiGroups: ["platform.example.com"]
    resources: ["resourcequotapolicies", "resourcequotapolicies/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "delete"]
