apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rqe-controller-binding
subjects:
  - kind: ServiceAccount
    name: rqe-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rqe-controller
  apiGroup: rbac.authorization.k8s.io
