global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'controller'
    static_configs:
      - targets: ['host.docker.internal:2112']

  - job_name: 'webhook'
    static_configs:
      - targets: ['host.docker.internal:2113']
